### ISSUE TITLE
Node-RED can't locate bindings file for serialport

### ISSUE THREAD

**Issue by thatcadguy** [FreeWaveTechnologies/ZumIQ#11]
I tried to create a simple flow using the Modbus-Getter block and it crashed Node-RED. Here's the readout from the commandline:

```devuser@freewave-ib:~$ node-red
8 Feb 18:57:06 - [info]

Welcome to Node-RED
===================

8 Feb 18:57:06 - [info] Node-RED version: v0.19.5
8 Feb 18:57:06 - [info] Node.js  version: v8.15.0
8 Feb 18:57:06 - [info] Linux 3.14.1 arm LE
8 Feb 18:57:09 - [info] Loading palette nodes
8 Feb 18:57:12 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
8 Feb 18:57:12 - [warn] rpi-gpio : Cannot find Pi RPi.GPIO python library
8 Feb 18:57:20 - [warn] ------------------------------------------------------
8 Feb 18:57:20 - [warn] [node-red/sentiment] Error: Cannot find module '../build/AFINN.json'
8 Feb 18:57:20 - [warn] ------------------------------------------------------
8 Feb 18:57:20 - [info] Settings file  : /home/devuser/.node-red/settings.js
8 Feb 18:57:20 - [info] Context store  : 'default' [module=memory]
8 Feb 18:57:20 - [info] User directory : /home/devuser/.node-red
8 Feb 18:57:20 - [warn] Projects disabled : editorTheme.projects.enabled=false
8 Feb 18:57:20 - [info] Flows file     : /home/devuser/.node-red/flows_freewave-ib.json
8 Feb 18:57:21 - [info] Server now running at http://127.0.0.1:1880/
8 Feb 18:57:21 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

8 Feb 18:57:21 - [info] Starting flows
8 Feb 18:57:21 - [info] Started flows
8 Feb 18:57:22 - [red] Uncaught Exception:
8 Feb 18:57:22 - Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/node-red-contrib-modbus/node_modules/modbus-serial/node_modules/serialport/build/serialport.node
 → /usr/lib/node_modules/node-red-contrib-modbus/node_modules/modbus-serial/node_modules/serialport/build/Debug/serialport.node
 → /usr/lib/node_modules/node-red-contrib-modbus/node_modules/modbus-serial/node_modules/serialport/build/Release/serialport.node
 → /usr/lib/node_modules/node-red-contrib-modbus/node_modules/modbus-serial/node_modules/serialport/out/Debug/serialport.node
 → /usr/lib/node_modules/node-red-contrib-modbus/node_modules/modbus-serial/node_modules/serialport/Debug/serialport.node
 → /usr/lib/node_modules/node-red-contrib-modbus/node_modules/modbus-serial/node_modules/serialport/out/Release/serialport.node
 → /usr/lib/node_modules/node-red-contrib-modbus/node_modules/modbus-serial/node_modules/serialport/Release/serialport.node
 → /usr/lib/node_modules/node-red-contrib-modbus/node_modules/modbus-serial/node_modules/serialport/build/default/serialport.node
 → /usr/lib/node_modules/node-red-contrib-modbus/node_modules/modbus-serial/node_modules/serialport/compiled/8.15.0/linux/arm/serialport.node
    at bindings (/usr/lib/node_modules/node-red-contrib-modbus/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/node-red-contrib-modbus/node_modules/modbus-serial/node_modules/serialport/lib/bindings/linux.js:2:36)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/node-red-contrib-modbus/node_modules/modbus-serial/node_modules/serialport/lib/bindings/auto-detect.js:16:22)
devuser@freewave-ib:~$
```

I tried manually installing serialport and node-red-contrib-modbus globally, didn't make a difference.

**Comment by thatcadguy** [comment]
I tried running `sudo node-gyp configure build` in the directory in question and it failed to build. Ended up uninstalling Node.js 8 and installing 10.
